### ISSUE TITLE
Clarification on the button inputs for 4-stopwatch

### ISSUE THREAD

**Issue by bingthegreat93** [m8pple/eie1_fpga_lab#2]
1) For the push-buttons BUTTON0 to 2 of the stopwatch, are we expected to detect the rising/falling edge of the push-buttons? Or are the functions only executed whenever the push-buttons are pressed down? 

For example, would a single press of the reset button permanently drive my counter values to 0000, or would the values only be driven to 0000 while I am pressing on the button?

2) After pressing the "split" button once to "pause" the display, what does the subsequent press on the same button do? Does it "unpause" the display or show the timing of the second "lap"?

**Comment by m8pple** [comment]
1. The reset button should reset it to zero, and it will then stick at zero until the start button is
   pressed. So you could treat it as either occurring on the rising edge of the reset button (i.e.
   the push part), or as occurring while the reset is being held down (the hold part). Making it
   reset on the fall (the release) probably doesn't make sense.
   
   Either way, after the button is released it should stick at zero.
   
   I could see an ambiguity with people pressing Start and Reset at the same time, so I'll
   update the spec to say that cases where two buttons are pushed are considered illegal
   inputs, with [undefined behaviour](http://en.wikipedia.org/wiki/Undefined_behavior).
2. You have a good point with the split functionality - my intention was that people
   would hold it down to see the split, then it carries on (unpauses), but that reflects
   my experience with an ancient Casio watch, and isn't really reflected in the spec.
   I'll update it to make it more rigorous.

Thanks.
